// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUv-J0LhzCXsP6-r8hQEK99wq41ghnVHE',
    appId: '1:52196197674:web:c4d0b3eeb40d700a048a53',
    messagingSenderId: '52196197674',
    projectId: 'simple-molkky-score',
    authDomain: 'simple-molkky-score.firebaseapp.com',
    storageBucket: 'simple-molkky-score.firebasestorage.app',
    measurementId: 'G-NP2XF6PCYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjbScMSf1VnFhdTA6tYgwC_cIoEwWnS3Q',
    appId: '1:52196197674:android:dc926183a969df12048a53',
    messagingSenderId: '52196197674',
    projectId: 'simple-molkky-score',
    storageBucket: 'simple-molkky-score.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoQ7opWmIxlc4VqmW44vyhNN4EJJ3ugGU',
    appId: '1:52196197674:ios:fb8404f777a0a2b0048a53',
    messagingSenderId: '52196197674',
    projectId: 'simple-molkky-score',
    storageBucket: 'simple-molkky-score.firebasestorage.app',
    iosBundleId: 'com.example.simpleMolkkyScore',
  );
}
